data "aws_iot_endpoint" "ats" {
  endpoint_type = "iot:Data-ATS"
}

# ----------------------------------------------------------------------------
# One thing + X.509 certificate per device
# ----------------------------------------------------------------------------

resource "aws_iot_thing" "device" {
  for_each = toset(var.device_ids)

  name = each.value
}

# The private key is generated by AWS and stored in the Terraform state:
# keep the state private (see README).
resource "aws_iot_certificate" "device" {
  for_each = toset(var.device_ids)

  active = true
}

resource "aws_iot_thing_principal_attachment" "device" {
  for_each = toset(var.device_ids)

  thing     = aws_iot_thing.device[each.key].name
  principal = aws_iot_certificate.device[each.key].arn
}

resource "aws_iot_policy_attachment" "device" {
  for_each = toset(var.device_ids)

  policy = aws_iot_policy.device.name
  target = aws_iot_certificate.device[each.key].arn
}

# ----------------------------------------------------------------------------
# Least-privilege device policy: a certificate can only connect as its own
# thing, publish upload requests and receive replies on its own topic.
# ----------------------------------------------------------------------------

locals {
  iot_arn_prefix = "arn:aws:iot:${var.aws_region}:${local.account_id}"
}

data "aws_iam_policy_document" "device" {
  statement {
    sid       = "ConnectAsOwnThing"
    actions   = ["iot:Connect"]
    resources = ["${local.iot_arn_prefix}:client/$${iot:Connection.Thing.ThingName}"]

    condition {
      test     = "Bool"
      variable = "iot:Connection.Thing.IsAttached"
      values   = ["true"]
    }
  }

  statement {
    sid       = "PublishUploadRequests"
    actions   = ["iot:Publish"]
    resources = ["${local.iot_arn_prefix}:topic/${local.topic_request}"]
  }

  statement {
    sid       = "SubscribeOwnReplies"
    actions   = ["iot:Subscribe"]
    resources = ["${local.iot_arn_prefix}:topicfilter/${local.topic_response_prefix}/$${iot:Connection.Thing.ThingName}"]
  }

  statement {
    sid       = "ReceiveOwnReplies"
    actions   = ["iot:Receive"]
    resources = ["${local.iot_arn_prefix}:topic/${local.topic_response_prefix}/$${iot:Connection.Thing.ThingName}"]
  }
}

resource "aws_iot_policy" "device" {
  name   = "${local.name}-device"
  policy = data.aws_iam_policy_document.device.json
}

# ----------------------------------------------------------------------------
# Rule: upload request -> GenerateUploadURL Lambda
# clientid() is the authenticated client ID, so devices cannot impersonate others.
# ----------------------------------------------------------------------------

resource "aws_iot_topic_rule" "upload_request" {
  name        = replace("${local.name}_upload_request", "-", "_")
  description = "Forwards ESP32 upload requests to the GenerateUploadURL Lambda"
  enabled     = true
  sql         = "SELECT *, clientid() AS client_id FROM '${local.topic_request}'"
  sql_version = "2016-03-23"

  lambda {
    function_arn = aws_lambda_function.generate_upload_url.arn
  }

  error_action {
    cloudwatch_logs {
      log_group_name = aws_cloudwatch_log_group.iot_rule_errors.name
      role_arn       = aws_iam_role.iot_rule_errors.arn
    }
  }
}

resource "aws_lambda_permission" "iot_invoke_generate_upload_url" {
  statement_id  = "AllowIoTRuleInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.generate_upload_url.function_name
  principal     = "iot.amazonaws.com"
  source_arn    = aws_iot_topic_rule.upload_request.arn
}

resource "aws_cloudwatch_log_group" "iot_rule_errors" {
  name              = "/aws/iot/${local.name}/rule-errors"
  retention_in_days = var.log_retention_days
}

data "aws_iam_policy_document" "iot_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["iot.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "iot_rule_errors" {
  name               = "${local.name}-iot-rule-errors"
  assume_role_policy = data.aws_iam_policy_document.iot_assume.json
}

resource "aws_iam_role_policy" "iot_rule_errors" {
  name = "write-rule-errors"
  role = aws_iam_role.iot_rule_errors.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["logs:CreateLogStream", "logs:PutLogEvents"]
      Resource = "${aws_cloudwatch_log_group.iot_rule_errors.arn}:*"
    }]
  })
}
